package com.jdevbook.chap7.model.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CourseImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public CourseImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"CourseId_Rule_0", "The CourseId has to be between 10 and 1000"},
    {"Course_Rule_0", "CourseId not unique"}};
}