package com.jdevbook.chap8;
/**
 * Generated by the Oracle9i JDeveloper Web Services Interface Generator
 * Date Created: Tue Oct 07 16:57:41 GMT+05:30 2003
 * 
 * This interface lists the subset of public methods that you
 * selected for inclusion in your web service's public interface.
 * It is referenced in the web.xml deployment descriptor for this service.
 * 
 * This file should not be edited.
 */

public interface IMyWebService1 
{
  public String numberSquare(int number);
}
