package com.jdevbook.chap8;
import oracle.soap.transport.http.OracleSOAPHTTPConnection;
import org.apache.soap.encoding.soapenc.BeanSerializer;
import org.apache.soap.encoding.SOAPMappingRegistry;
import org.apache.soap.util.xml.QName;
import java.net.URL;
import org.apache.soap.Constants;
import org.apache.soap.Fault;
import org.apache.soap.SOAPException;
import org.apache.soap.rpc.Call;
import org.apache.soap.rpc.Parameter;
import org.apache.soap.rpc.Response;
import java.util.Vector;
import java.util.Properties;
/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Oct 08 23:05:22 GMT+05:30 2003
 * WSDL URL: file:/C:/JDeveloper/jdev/mywork/WebServApp/Project/src/com/jdevbook/chap8/IMyWebService1.wsdl
 */

public class MyWebService1Stub 
{
  public MyWebService1Stub()
  {
    System.setProperty("oracle.soap.transport.noHTTPClient", "true");
    m_httpConnection = new OracleSOAPHTTPConnection();
    m_smr = new SOAPMappingRegistry();
    Properties props = new Properties();
    props.put(OracleSOAPHTTPConnection.AUTH_TYPE, "basic");
    props.put(OracleSOAPHTTPConnection.USERNAME, "your_username");
    props.put(OracleSOAPHTTPConnection.PASSWORD, "your_password");
    props.put(OracleSOAPHTTPConnection.PROXY_AUTH_TYPE, "basic");
    props.put(OracleSOAPHTTPConnection.PROXY_USERNAME, "proxy_username");
    props.put(OracleSOAPHTTPConnection.PROXY_PASSWORD, "proxy_password");
    props.put(OracleSOAPHTTPConnection.PROXY_HOST, "proxy_host");
    props.put(OracleSOAPHTTPConnection.PROXY_PORT, "80");
    m_httpConnection.setProperties(props);
  }

  public static void main(String[] args)
  {
    try
    {
      MyWebService1Stub stub = new MyWebService1Stub();
      // Add your own code here.
    }
    catch(Exception ex)
    {
      ex.printStackTrace();
    }

  }

  private String _endpoint = "http://mycomp:8988/WebServApp-Project-context-root/MyWebService1";

  public String getEndpoint()
  {
    return _endpoint;
  }

  public void setEndpoint(String endpoint)
  {
    _endpoint = endpoint;
  }

  private OracleSOAPHTTPConnection m_httpConnection = null;
  private SOAPMappingRegistry m_smr = null;

  public String numberSquare(Integer number) throws Exception
  {
    String returnVal = null;

    URL endpointURL = new URL(_endpoint);
    Call call = new Call();
    call.setSOAPTransport(m_httpConnection);
    call.setTargetObjectURI("MyWebService1");
    call.setMethodName("numberSquare");
    call.setEncodingStyleURI(Constants.NS_URI_SOAP_ENC);

    Vector params = new Vector();
    params.addElement(new Parameter("number", java.lang.Integer.class, number, null));
    call.setParams(params);

    call.setSOAPMappingRegistry(m_smr);

    Response response = call.invoke(endpointURL, "");

    if (!response.generatedFault())
    {
      Parameter result = response.getReturnValue();
      returnVal = (String)result.getValue();
    }
    else
    {
      Fault fault = response.getFault();
      throw new SOAPException(fault.getFaultCode(), fault.getFaultString());
    }

    return returnVal;
  }

  public void setMaintainSession(boolean maintainSession)
  {
    m_httpConnection.setMaintainSession(maintainSession);
  }

  public boolean getMaintainSession()
  {
    return m_httpConnection.getMaintainSession();
  }

  public void setTransportProperties(Properties props)
  {
    m_httpConnection.setProperties(props);
  }

  public Properties getTransportProperties()
  {
    return m_httpConnection.getProperties();
  }
}