package com.jdevbook.chap8;
/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Oct 08 23:05:22 GMT+05:30 2003
 * WSDL URL: file:/C:/JDeveloper/jdev/mywork/WebServApp/Project/src/com/jdevbook/chap8/IMyWebService1.wsdl
 */

public interface MyWebService1Skeleton 
{
  public String numberSquare(Integer number) throws Exception;
}