package com.jdevbook.chap7.model;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class AppModuleImpl extends ApplicationModuleImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AppModuleImpl()
  {
  }

  /**
   * 
   *  Container's getter for StudentView1
   */
  public StudentViewImpl getStudentView1()
  {
    return (StudentViewImpl)findViewObject("StudentView1");
  }

  /**
   * 
   *  Container's getter for CourseView1
   */
  public CourseViewImpl getCourseView1()
  {
    return (CourseViewImpl)findViewObject("CourseView1");
  }

  /**
   * 
   *  Container's getter for StudentView2
   */
  public StudentViewImpl getStudentView2()
  {
    return (StudentViewImpl)findViewObject("StudentView2");
  }

  /**
   * 
   *  Container's getter for StudentCourseFk1Link1
   */
  public ViewLinkImpl getStudentCourseFk1Link1()
  {
    return (ViewLinkImpl)findViewLink("StudentCourseFk1Link1");
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("com.jdevbook.chap7.model", "AppModuleLocal");
  }

  /**
   * 
   *  Container's getter for JavaCourseView1
   */
  public JavaCourseViewImpl getJavaCourseView1()
  {
    return (JavaCourseViewImpl)findViewObject("JavaCourseView1");
  }
}