package com.jdevbook.chap7.model;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CourseImpl extends EntityImpl 
{
  public static final int COURSEID = 0;
  public static final int COURSENAME = 1;
  public static final int STUDENT = 2;










  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public CourseImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("com.jdevbook.chap7.model.Course");
    }
    return mDefinitionObject;
  }











  /**
   * 
   *  Gets the attribute value for CourseId, using the alias name CourseId
   */
  public Number getCourseId()
  {
    return (Number)getAttributeInternal(COURSEID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CourseId
   */
  public void setCourseId(Number value)
  {
    setAttributeInternal(COURSEID, value);
  }

  /**
   * 
   *  Gets the attribute value for CourseName, using the alias name CourseName
   */
  public String getCourseName()
  {
    return (String)getAttributeInternal(COURSENAME);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CourseName
   */
  public void setCourseName(String value)
  {
    setAttributeInternal(COURSENAME, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case COURSEID:
        return getCourseId();
      case COURSENAME:
        return getCourseName();
      case STUDENT:
        return getStudent();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case COURSEID:
        setCourseId((Number)value);
        return;
      case COURSENAME:
        setCourseName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getStudent()
  {
    return (RowIterator)getAttributeInternal(STUDENT);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number courseId)
  {
    return new Key(new Object[] {courseId});
  }










}