package com.jdevbook.chap7.model;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class JavaCourseViewImpl extends ViewObjectImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public JavaCourseViewImpl()
  {
  }
}