package com.jdevbook.chap7.model;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class StudentImpl extends EntityImpl 
{
  public static final int STUDENTID = 0;
  public static final int STUDENTNAME = 1;
  public static final int COURSEID = 2;
  public static final int COURSE = 3;








  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public StudentImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("com.jdevbook.chap7.model.Student");
    }
    return mDefinitionObject;
  }









  /**
   * 
   *  Gets the attribute value for StudentId, using the alias name StudentId
   */
  public Number getStudentId()
  {
    return (Number)getAttributeInternal(STUDENTID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for StudentId
   */
  public void setStudentId(Number value)
  {
    setAttributeInternal(STUDENTID, value);
  }

  /**
   * 
   *  Gets the attribute value for StudentName, using the alias name StudentName
   */
  public String getStudentName()
  {
    return (String)getAttributeInternal(STUDENTNAME);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for StudentName
   */
  public void setStudentName(String value)
  {
    setAttributeInternal(STUDENTNAME, value);
  }

  /**
   * 
   *  Gets the attribute value for CourseId, using the alias name CourseId
   */
  public Number getCourseId()
  {
    return (Number)getAttributeInternal(COURSEID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CourseId
   */
  public void setCourseId(Number value)
  {
    setAttributeInternal(COURSEID, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case STUDENTID:
        return getStudentId();
      case STUDENTNAME:
        return getStudentName();
      case COURSEID:
        return getCourseId();
      case COURSE:
        return getCourse();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case STUDENTID:
        setStudentId((Number)value);
        return;
      case STUDENTNAME:
        setStudentName((String)value);
        return;
      case COURSEID:
        setCourseId((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   *  Gets the associated entity CourseImpl
   */
  public CourseImpl getCourse()
  {
    return (CourseImpl)getAttributeInternal(COURSE);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity CourseImpl
   */
  public void setCourse(CourseImpl value)
  {
    setAttributeInternal(COURSE, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number studentId)
  {
    return new Key(new Object[] {studentId});
  }








}